---
# This playbook deploys the whole application stack in this site.

- name: Apply common configuration to all nodes
  hosts: all
  remote_user: pi
  become: yes
  become_user: root

  roles:
    - common
    - ruby
