---
# This playbook contains common plays that will be run on all nodes.

- name: Install ntp
  apt: name=ntp update_cache=true
  become: yes

- name: Configure ntp
  template: src=ntp.conf dest=/etc/ntp.conf
  become: yes
  notify: restart ntp
