- name: Install ntp
  apt: name=ntp update_cache=true

- name: Configure ntp
  template: src=ntp.conf dest=/etc/ntp.conf
  notify: restart ntp

- name: Stop ntp
  service: name=ntp state=stopped

- name: Synchronize time
  raw: sudo ntpd -qg
  notify: restart ntp
