- name: Install ntp
  apt: name=ntp update_cache=true
  become: yes

- name: Configure ntp
  template: src=ntp.conf dest=/etc/ntp.conf
  become: yes
  notify: restart ntp

- name: Stop ntp
  service: name=ntp state=stopped
  become: yes

- name: Synchronize time
  raw: sudo ntpd -qg
  notify: restart ntp
